version: '3.8'

networks:
  myappnetwork:
    driver: bridge
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=upslp
    networks:
      - myappnetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: devi7uke/docker-app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - myappnetwork